// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/6/2026, 1:20:29 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/plugins/**/*.{js,ts,mjs}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/composables/**/*.{js,ts,mjs}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/utils/**/*.{js,ts,mjs}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/arthur.kielbasa/PhpstormProjects/lovely-reminder/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;